<br> 

## About this website

I wanted to create a blog where I can explore questions I have and show how I use data to do so... so here it is. 

<br>

## About Me

I'm an INTJ, which means I like spending time thinking about the big picture and then carrying out tasks to make it work. It also means I don't just accept ideas, but have to compare the evidence for them against the representation of the world I've built. I try to use the scientific method to do this, but sometimes there are things that just appeal to me because of how well they fit other concepts I've adopted. 

I went to high school at the [Illinois Math and Science Academy](https://www.imsa.edu/), which is a publicly funded residential school created to help prepare students for STEM degrees. Instead I choose to study Economics at [Occidental College](http://www.oxy.edu/). 

After graduating, I moved back to Illinois to be with my girlfriend (now wife) as she attended UIC. I started an internship in marketing analytics, then moved on to a full-time job as a Housing Specialist -- a position with a variety of duties surrounding the caseload management of the [Housing Choice Voucher Program](http://portal.hud.gov/hudportal/HUD?src=/program_offices/public_indian_housing/programs/hcv/about/fact_sheet). After learning a great deal about Section 8 and the HCVP, I switched to the other side and helped a property management company fix their paperwork and accounting for subsidized rentals. In only 6 months I had automated most of my job and was only working 2-3 hours per day. I was able to transition to a position as a Management Analyst for [Nan McKay & Associates](http://www.nanmckay.com).

In that role, which was a first for the company as they started their biggest contract to date, I found a niche and really thrived. I realized that I had a competitive advantage in data analysis. I had worked for the IT department in college and had studied econometrics and statistics, so it's not a surprise looking back, but at the time I didn't know that was even a job. I found myself able to greatly improve the ability to drive measurable results and influence the strategy of the company. 

After 4 years of being an analyst, I started thinking about what I wanted to do with my life. I was researching careers and I came across Data Science. I had never heard of it, but I realized I was already doing a lot of it. I started to explore machine learning and after applying to a project at work I realized right away just how powerful of a tool it was and how much potential it had to reshape the way I tackle all sorts of problems. I decided then I wanted to devote my career to this and enrolled in the [MIDS Program through UC Berkeley](https://datascience.berkeley.edu)

After one semester, I was promoted to lead a team of analysts. I started teaching SQL, Python and R to my team so that we could automate as many of the recurring reports as possible, which would then allow us to take on most impactful projects. Before long, my talents in a quickly growing market lead me elsewhere.

For the last year, I've been at [Raise Marketplace](https://www.raise.com). Here I try to make sense of a new industry, share insights with as many of the decision makers as I can, and improve the analytical thinking of everyone I work with. I completed my graduate degree in May and am looking to make my mark on the world. 
